# Generated by Django 4.1.3 on 2022-12-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_coche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m2', models.CharField(max_length=100)),
                ('habitaciones', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=100)),
                ('anios', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
